### ISSUE TITLE
we need to uncompress raw.xz files before creating AMIs out of them

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/fedimg#101]
We're [getting reports](https://pagure.io/cloud-sig/issue/286) of instances that aren't able to boot. I inspected one of these AMIs and it turns out the data on the volume is xz compressed data. **We need to decompress the data before creating a volume/snapshot/AMI out of it.** I imagine it would happen somewhere around [here](https://github.com/fedora-infra/fedimg/blob/0dbce07fdd6cdc996e4e1d5613d1cb0af87ba0cb/fedimg/utils.py#L139) in the code.

Just to verify I took the xz compressed data from one of these AMIs, decompressed it, and wrote it back out to the volume and then booted the same instance using the uncompressed disk.

**Comment by sayanchowdhury** [comment]
@dustymabe The PR for this is already there #99 and the hotfix is already in prod.

**Comment by sayanchowdhury** [comment]
This issue has been fixed in [`2.0.0`](https://github.com/fedora-infra/fedimg/releases/tag/2.0.0). Closing this issue.
