### ISSUE TITLE
fedimg doesn't remove images after upload

### ISSUE THREAD

**Issue by nirik** [fedora-infra/fedimg#105]
on fedimg01.phx2.fedoraproject.org:
# du -sh /tmp
13G     /tmp

all these are dirs with images, some of which I deleted to get space under control. 

 ls -lR tmpjI3dm0
tmpjI3dm0:
total 160400
-rw-r--r--. 1 fedmsg fedmsg 164249592 Apr 14 13:02 Fedora-Cloud-Base-28-20180414.n.0.x86_64.raw.xz

make sure fedimg cleans up after it uploads (or fails to).

**Comment by sayanchowdhury** [comment]
Thanks for reporting, @nirik. I've found a issue in the code that resolves this issue to great extent but still it leaves those dirs lying around sometimes. 
I'll try to fix this on priority.

**Comment by nirik** [comment]
Great. Thanks for looking into it!

**Comment by sayanchowdhury** [comment]
#112 partially fixed the issue. I opened the PR #130 which should fix the issue.

**Comment by sayanchowdhury** [comment]
This issue has been fixed in [`2.0.0`](https://github.com/fedora-infra/fedimg/releases/tag/2.0.0) and deployed in production. The tmp directories are getting cleaned up automatically. I'm closing this issue for now, if this issue misses some not-thought of cases then I'll open this issue again.
