### ISSUE TITLE
Fedimg is unable to process Fedora 28 Atomic Two Week compose

### ISSUE THREAD

**Issue by sinnykumari** [fedora-infra/fedimg#115]
We recently started running compose for [F28 Two Week](https://kojipkgs.fedoraproject.org/compose/twoweek/Fedora-Atomic-28-20180424.4/) . It seems fedimg fail to process it due to following error from log:

```
File "/usr/lib/python2.7/site-packages/moksha/hub/api/consumer.py", line 206, in _do_work
fedimg01 fedmsg-hub: self.consume(message)
File "/usr/lib/python2.7/site-packages/fedimg/consumers.py", line 105, in consume
images_meta.extend(get_value_from_dict(
AttributeError: 'NoneType' object has no attribute 'extend'
```

This is happening because, we don't have cloud-base images to process in F28 Two Week compose.

**Comment by sinnykumari** [comment]
PR for fix - https://github.com/fedora-infra/fedimg/pull/116

**Comment by sayanchowdhury** [comment]
The PR has been merged. Closing.
