### ISSUE TITLE
support for updates and updates-testing composes

### ISSUE THREAD

**Issue by dustymabe** [fedora-infra/fedimg#125]
We are going to start making qcow image artifacts in our updates and updates-testing compose runs. We need to be able to pick these up in fedimg so they can be uploaded to AWS. For updates-testing runs maybe we don't default to uploading them to AWS, but for updates run we do.

**Comment by dustymabe** [comment]
one example where an updates-testing run has qcows: https://kojipkgs.fedoraproject.org/compose/updates/Fedora-28-updates-testing-20180429.1/compose/AtomicHost/x86_64/images/

**Comment by sayanchowdhury** [comment]
This feature has been pushed and deployed. Closing.

**Comment by abitrolly** [comment]
Not closed yet.

**Comment by sayanchowdhury** [comment]
Now confirmed that the issue is closed
