### ISSUE TITLE
possibly produce virt-builder index.asc files?

### ISSUE THREAD

**Issue by mattdm** [fedora-infra/fedimg#13]
See https://lists.fedoraproject.org/pipermail/cloud/2014-June/003950.html and particularly the reference to http://libguestfs.org/virt-builder.1.html -- maybe we could produce this automatically as part of the image upload?

(Not sure that this is the right place. Just wanted to note it as a possibility.)

**Comment by ralphbean** [comment]
We decided that this doesn't make sense for fedimg.
