### ISSUE TITLE
Change hard-code 12 GB volume size

### ISSUE THREAD

**Issue by a13m** [fedora-infra/fedimg#15]
Right now, it looks like this code is always generating 12 GB volumes.  Given that most of our images are only 3 GB, this seems like a waste of space & money.  It should generally be possibly to inspect the size of the image (or even retrieve the information from the TDL file in the koji task) so that we don't have to guess the size.

**Comment by oddshocks** [comment]
I fixed this over the holidays. Images are now registered as our minimum of 3 GB.

Thanks for the report. :)
