### ISSUE TITLE
Write supporting tools for sysadmins

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedimg#35]
we need some tools:

- [ ] we need something to list all the running instances in AWS (using the keys in the fedimg config)
- [ ] we need something to kill a single instance

Combining those two, we can clean up the AWS account when it gets congested.  We can clean it from the CLI on ``fedimg01`` instead of having to bug someone with rights to the AWS console to go and do it by hand (dgilmore).

**Comment by kushaldas** [comment]
I am adding a command kill_ec2_nodes.py which can kill any instance running more than 2 hours using the same access details.
