### ISSUE TITLE
Reorganize the way we upload images to AWS

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedimg#42]
We start up a helper image and then download the image we really want, and write it out to a snapshot.

Then we copy the image to all the other regions.

Apparently, according to gholms, we can write the image directly to s3 which should allow us to skip that first step.

**Comment by dustymabe** [comment]
yeah, we don't even need to write to s3 - you can just create an ebs volume directly and then create a snapshot from it. Here is a gist where I did that. It's using older tools but should still be able to do the same with the newer awscli tools.

https://gist.github.com/dustymabe/3d53cfe6b9ae32c5e2fb
