### ISSUE TITLE
Remove scratch-task based uploading

### ISSUE THREAD

**Issue by ralphbean** [fedora-infra/fedimg#48]
According to [this releng ticket](https://fedorahosted.org/rel-eng/ticket/6304) it should be dead soon.

I added build-based uploading in #47, but didn't remove the scratch-task based uploading yet.  That should be done, just to clean the code and keep it sane.

**Comment by dustymabe** [comment]
@ralphbean so once this issue is fixed then that will unblock https://fedorahosted.org/rel-eng/ticket/6304  ?

**Comment by ralphbean** [comment]
I think so, yes. (since we don't want to be uploading all those throwaway scratch builds willy-nilly, right?)

**Comment by dustymabe** [comment]
@ralphbean right. @sayanchowdhury do you think this is something that can be easily done?

**Comment by sayanchowdhury** [comment]
I have modified the consumer to listen to the compose messages. PR #51

**Comment by sayanchowdhury** [comment]
This has been pushed to production. Closing!
