### ISSUE TITLE
README 'trigger_upload' instructions out of date

### ISSUE THREAD

**Issue by euank** [fedora-infra/fedimg#72]
The readme instructions claim I can run `./bin/trigger_upload.py SOME_RAWXZ_URL` to upload things.

That script still has `from fedimg.util import virt_types_from_url` even though that import was [changed](https://github.com/fedora-infra/fedimg/commit/b0b3569667c3441f3fbd94063a1860be478453c7#diff-c39463057aede36960b3a421e411aff5), and even after fixing the import issues, the script still doesn't run.

How is fedimg typically run? Should `trigger_upload` be fixed or deleted?

**Comment by sayanchowdhury** [comment]
The README & the trigger_upload script both needs to be updated. I recently push a hotfix to the prod. I will port the related patch back here.

**Comment by euank** [comment]
It seems odd to push a fix to prod before putting it in the open source repository for an AGPL project. It certainly seems to be against the spirit of the license to me unless prod provides the currently running source code through some alternate means.

Is there an alternate source I can consult to figure out how to run this while I wait for you to mirror over the change?

**Comment by sayanchowdhury** [comment]
Prod is running a older version i.e 0.7.4 so had to be hotfixed via [infrastructure ansible](https://infrastructure.fedoraproject.org/cgit/ansible.git/tree/roles/fedimg/files/trigger_upload.py). I have created a PR #76 to updated the README and the script

**Comment by sayanchowdhury** [comment]
This has been fixed.
